force-app/main/default/objects/Commentary__c/Commentary__c.object-meta.xml
<CustomObject>
    <label>Commentary</label>
    <nameField>
        <label>Commentary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commentaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commentary__c/fields/Commentary__c.field-meta.xml
<CustomField>
    <fullName>Commentary__c</fullName>
    <label>Commentary</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commentary__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommentaryContrller.cls
public with sharing class CommentaryContrller {
    @AuraEnabled
    public static Commentary__c saveNewCommentary(String commentId, String comment, Decimal rating, String productId){
        
        Commentary__c newObject = 
        commentId == ''? new Commentary__c() : 
        new Commentary__c(
            Id = commentId
        );
      
        newObject.Commentary__c = comment;
        newObject.rating__c = rating;
        newObject.Product__c = productId;
        newObject.Approval__c = false;
        
        upsert newObject;
        return newObject;
    }

    @AuraEnabled(cacheable=true)
    public static List<Commentary__c> getCommentList(String productId){
        List<Commentary__c> productComment = [SELECT Id, OwnerId, Name, CreatedById, LastModifiedDate, Product__c,
         CreatedBy.Name, rating__c, Commentary__c, Approval__c
        FROM Commentary__c Where Product__c = :productId];
        return productComment;
    }
}