force-app/main/default/objects/Product2/fields/Custom_Description__c.field-meta.xml
<CustomField>
    <fullName>Custom_Description__c</fullName>
    <label>Custom Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Main_Photo__c.field-meta.xml
<CustomField>
    <fullName>Main_Photo__c</fullName>
    <label>Main Photo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Hot Deal</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductService.cls
public with sharing class ProductService {

    public class Product {
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String category;
        @AuraEnabled
        public double price;
        @AuraEnabled
        public double discountedPrice;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String image;
        @AuraEnabled
        public String description;
        @AuraEnabled
        public String providedCurrency;

        @AuraEnabled
        public Id pricebookEntryId;

        public Product(PricebookEntry entryOfProduct) {
            this.pricebookEntryId = entryOfProduct.Id;
            this.id = entryOfProduct.Product2.Id;
            this.name = entryOfProduct.Product2.Name;
            this.category = entryOfProduct.Product2.Family;
            this.price = entryOfProduct.UnitPrice;
            this.discountedPrice = entryOfProduct.UnitPrice;
            this.status = entryOfProduct.Product2.Status__c;
            this.image = entryOfProduct.Product2.Main_Photo__c;
            this.description = entryOfProduct.Product2.Custom_Description__c;
            this.providedCurrency = entryOfProduct.CurrencyIsoCode;
        }

        public OrderItem getOrderItem(Id orderId) {
            return new OrderItem(
                PricebookEntryId = this.pricebookEntryId,
                OrderId = orderId,
                Product2Id = this.id,
                UnitPrice = this.price,
                Quantity = 1
            );
        }
}
}