force-app/main/default/objects/Auction__c/Auction__c.object-meta.xml
<CustomObject>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Auction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Auctions</relationshipLabel>
    <relationshipName>Auctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Auction__c/fields/Start_Price__c.field-meta.xml
<CustomField>
    <fullName>Start_Price__c</fullName>
    <label>Start Price</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Auction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Auction__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Custom_Description__c.field-meta.xml
<CustomField>
    <fullName>Custom_Description__c</fullName>
    <label>Custom Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Main_Photo__c.field-meta.xml
<CustomField>
    <fullName>Main_Photo__c</fullName>
    <label>Main Photo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Hot Deal</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RecordPageController.cls
public with sharing class RecordPageController {
    
    @AuraEnabled(cacheable=true)
    public static ProductService.Product recieveRecordData(Id recordIdToDisplay) {
        try {


            
            PricebookEntry pricebookEntryOfProduct = [SELECT Id, UnitPrice, Product2Id, Product2.Custom_Description__c, Product2.Main_Photo__c, Pricebook2.IsStandard, Product2.Name,Product2.Family, Product2.Status__c
                                                     FROM PricebookEntry
                                                     WHERE Product2.Id =: recordIdToDisplay AND Pricebook2.IsStandard = TRUE];
 

            ProductService.Product wrapperToDisplay = new ProductService.Product(pricebookEntryOfProduct);



            return wrapperToDisplay;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<ContentDocumentLink> getIdsOfDocumentContentVersion(String productId) {


        List<ContentDocumentLink> contentVersionOfUploadedPhotos = [SELECT ContentDocument.LatestPublishedVersionId 
                                                                    FROM ContentDocumentLink 
                                                                    WHERE LinkedEntityId =: productId];



        return contentVersionOfUploadedPhotos;

    }

    @AuraEnabled(cacheable=true)
    public static List<Auction__c> checkIfProductIsOnAuction(Id idOfProduct){
        try {

            System.debug(idOfProduct);

        List <Auction__c> auctionToBeChecked = [SELECT End_Date__c, Start_Date__c, Start_Price__c, Status__c, UserId__c
                                                FROM Auction__c
                                                WHERE Product__c =: idOfProduct];

        System.debug(auctionToBeChecked);

        return auctionToBeChecked;

                
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updatePriceAfterAuction(Id idOfProduct, Decimal newPrice, Id idOfUser){
        try {
        
            PricebookEntry pricebookEntryOfProductToPriceChange = [SELECT Id, UnitPrice, Product2Id, Product2.Custom_Description__c, Product2.Main_Photo__c, Pricebook2.IsStandard, Product2.Name,Product2.Family, Product2.Status__c
                                                                  FROM PricebookEntry
                                                                  WHERE Product2.Id =: idOfProduct AND Pricebook2.IsStandard = TRUE];

            Auction__c auctionToBeUpdated = [SELECT Id
                                            FROM Auction__c
                                            WHERE Product__c =: idOfUser];

        pricebookEntryOfProductToPriceChange.UnitPrice = newPrice;

        auctionToBeUpdated.UserId__c = idOfUser;

        update auctionToBeUpdated;

        update pricebookEntryOfProductToPriceChange;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}